AP-2008-11-19-0: Bugfix:      Dbwriter is not starting after reboot of the machine                  Bugster:     6764942                  Issue:       2790                  Review:      DG

diff --git a/source/dbwriter/util/sgedbwriter_template b/source/dbwriter/util/sgedbwriter_template
--- a/source/dbwriter/util/sgedbwriter_template
+++ b/source/dbwriter/util/sgedbwriter_template
@@ -43,7 +43,7 @@
 # DB Writer Startup script template
 #
 # To see the usage of this script, run it with the -h option
-#                   
+#
 #---------------------------------------------------------------------------
 # The following lines provide the necessary info for adding a startup script
 # according to the Linux Standard Base Specification (LSB) 1.0.0 which can
@@ -57,7 +57,7 @@
 #
 ### BEGIN INIT INFO
 # Provides:       GENSGESVC
-# Required-Start: $network 
+# Required-Start: $network
 # Required-Stop:
 # Default-Start:  3 5
 # Default-Stop: 0 1 2 6
@@ -114,7 +114,7 @@ usage()
 {
    echo "usage: $0 [start|stop] [-debug] [-debug_port <port>] [-nosmf] [print <setting>] [-h]"
    echo "    start   start the dbwriter as background process (default)"
-   echo "    stop    stop the dbwriter"   
+   echo "    stop    stop the dbwriter"
    echo ""
    echo "    -debug              start the dbwriter in in debug mode"
    echo "    -debug_port <port>  port for debugging (default 8000)"
@@ -144,7 +144,7 @@ Shutdown()
    name=$1
    pidfile=$2
    if [ -r $pidfile ]; then
-      pid=`cat $pidfile` 
+      pid=`cat $pidfile`
       $UTILBIN_DIR/checkprog $pid $name > /dev/null
       if [ "$?" = 0 ]; then
          ExecuteAsAdmin kill -TERM $pid
@@ -160,7 +160,7 @@ Shutdown()
          sleep 30
          ExecuteAsAdmin kill -9 $pid
       fi
-   else 
+   else
 	  echo "Can not read pid file $pidfile"
 	  exit 1
    fi
@@ -170,13 +170,15 @@ CheckDbWriterRunning() {
    name=$1
    pidfile=$2
    i=0
-   while [ $i -lt 5 ]; do
+   while [ $i -lt 10 ]; do
       if [ -r $pidfile ]; then
-         pid=`cat $pidfile`
-         $UTILBIN_DIR/checkprog $pid $name > /dev/null
-         if [ "$?" = 0 ]; then
-            echo $pid
-            return 0
+         pid=`cat $pidfile 2>/dev/null`
+         if [ "$pid" != "" ]; then
+            $UTILBIN_DIR/checkprog $pid $name > /dev/null
+            if [ "$?" = 0 ]; then
+               echo $pid
+               return 0
+            fi
          fi
       fi
       sleep 2
@@ -216,7 +218,7 @@ ExecuteAsAdmin()
    if [ $ADMINUSER = default ]; then
       $*
    else
-      $UTILBIN_DIR/adminrun $ADMINUSER "$@" 
+      $UTILBIN_DIR/adminrun $ADMINUSER "$@"
    fi
 
    return 0
@@ -253,7 +255,7 @@ DetectSMFService()
    fi
    #Cluster name must be unique
    SGE_CLUSTER_NAME=`cat $SGE_ROOT/$SGE_CELL/common/cluster_name 2>/dev/null`
-   
+
    service="svc:/application/sge/$name:$SGE_CLUSTER_NAME"
 
    if [ -n "$SMF_FMRI" -a "$service" != "$SMF_FMRI" ]; then
@@ -287,11 +289,11 @@ Status() {
        if [ "$?" = 0 ]; then
           echo "dbwriter is running (pid $pid)"
           return 0
-       else 
+       else
           echo "dbwriter is not running"
           return 1
        fi
-    else 
+    else
        echo "dbwriter is not running"
        return 2
     fi
@@ -302,7 +304,7 @@ Status() {
 # Start the dbwriter
 # --------------------------------------------------------------------------
 startDBWriter() {
-   
+
    # --------------------------------------------------------------------------
    # Setup the classpath
    # Allow setting of an initial classpath, e.g. for running instrumented code
@@ -321,19 +323,19 @@ startDBWriter() {
         CP="$CP:$i"
      fi
    done
-   
+
    if [ "$JVMARGS" = "" ]; then
       JVMARGS="-classpath $CP"
    else
       JVMARGS="$JVMARGS -classpath $CP"
    fi
-   
+
    if [ "$JAVA_HOME" = "" ]; then
       JAVA=`which java`
-   else 
+   else
       JAVA=$JAVA_HOME/bin/java
    fi
-   
+
    DBWRITER_OPTIONS=""
    USE_DEFAULT_LOG_FILE=1
    USE_DEFAULT_PID_FILE=1
@@ -353,7 +355,7 @@ startDBWriter() {
       fi
       shift
    done
-   
+
    if [ $USE_DEFAULT_PID_FILE -eq 1 ]; then
       DBWRITER_OPTIONS="$DBWRITER_OPTIONS -pid $PID_FILE"
    fi
@@ -374,7 +376,7 @@ printSetting () {
      exit 1
    fi
    echo "printSetting got args: $*"
-   
+
    case "$1" in
       "pid_file")  echo "$PID_FILE"; exit 0;;
       "log_file")  echo "$LOG_FILE"; exit 0;;
@@ -398,14 +400,14 @@ while [ $# -gt 0 ]; do
      "-h")    usage; exit 0;;
      "-debug")
 	     DEBUG=true; shift;;
-     "-debug_port")	     
-	     shift 
+     "-debug_port")
+	     shift
              if [ $# -lt 1 ]; then
 		usage; exit 1;
 	     fi
              DEBUG_PORT=$1
              shift;;
-     "print") 
+     "print")
              PARAM="print"; shift;  break;;
      "start")
 	     PARAM=start; shift;;
@@ -482,10 +484,10 @@ case $PARAM in
            echo "ERROR: pid file $PID_FILE exists, but dbwriter (pid = $pid) is not running ";
            echo "       on this host. Inpect the \$SPOOL_DIR/dbwriter.log file to verify if ";
            echo "       dbwriter is not running on a different host. If it is not running, ";
-           echo "       delete the pid file." 
+           echo "       delete the pid file."
            exit $ERR_EXIT_CODE;;
         # 2 means pid file not found
-      esac       
+      esac
 
       checkSpoolDir $SPOOL_DIR
 
@@ -504,13 +506,13 @@ case $PARAM in
       else
          echo "starting dbwriter"
          JVMARGS="$JVMARGS -server"
-      fi 
+      fi
 
-      
+
       # set java.library.path and the data model (32-bit/64-bit)
       JVMARGS="$JVMARGS -Djava.library.path=@@JAVA_LIBRARY_PATH@@ @@JAVA_DATA_MODEL@@"
       export JVMARGS
-      
+
       if [ ! -f $LOG_FILE ]; then
          ExecuteAsAdmin touch $LOG_FILE
          if [ $? -ne 0 ]; then
@@ -518,14 +520,14 @@ case $PARAM in
             exit $ERR_EXIT_CODE
          fi
       fi
-      
+
       startDBWriter
 
       pid=`CheckDbWriterRunning java $PID_FILE`
       if [ $? -eq 0 ]; then
          [ -d /var/lock/subsys -a -w /var/lock/subsys ] && touch /var/lock/subsys/sgedbwriter
          echo "dbwriter started (pid=$pid)"
-      else 
+      else
          echo "dbwriter failed!"
          echo "Check log file $LOG_FILE"
          exit 1
@@ -543,7 +545,7 @@ case $PARAM in
    "print")
       printSetting $@;;
    *)
-      echo "invalid parameter $PARAM"   
+      echo "invalid parameter $PARAM"
       usage; exit 1;;
 esac
 
